Repository SuDaJo/MusicPlayer, pull requests merged in 2023-03, with the labels that each got.

#75 Feat/issue 70
  frontend/index.html
  frontend/static/css/navbar.css
  frontend/static/image/icon-chart-active.svg
  frontend/static/image/icon-chart.svg
  frontend/static/image/icon-myplaylist-active.svg
  frontend/static/image/icon-myplaylist.svg
  frontend/static/js/index.js
  frontend/static/js/views/Chart.js
Labels: Feat, Style, MarkUp, Pair

#77 Feat/issue 76
  frontend/static/css/home.css
  frontend/static/css/reset.css
  frontend/static/image/id_card.png
  frontend/static/js/json/memberData.json
  frontend/static/js/views/Home.js
Labels: Style, Pair

#78 Build: develop에서 main으로 merge
  .gitignore
  README.md
  frontend/_redirects
  frontend/index.html
  frontend/static/css/chart.css
  frontend/static/css/home.css
  frontend/static/css/myplaylist.css
  frontend/static/css/navbar.css
  frontend/static/css/playcontrol.css
  frontend/static/css/reset.css
  frontend/static/css/search.css
  frontend/static/css/style.css
  frontend/static/image/album-img.png
  frontend/static/image/album-title-img.png
  frontend/static/image/icon-arrow-left.svg
  frontend/static/image/icon-backward.svg
  frontend/static/image/icon-chart-active.svg
  frontend/static/image/icon-chart.svg
  frontend/static/image/icon-forward.svg
  frontend/static/image/icon-home-active.svg
  frontend/static/image/icon-home.svg
  frontend/static/image/icon-myplaylist-active.svg
  frontend/static/image/icon-myplaylist.svg
  frontend/static/image/icon-pause.svg
  frontend/static/image/icon-play-gray.svg
  frontend/static/image/icon-play-white.svg
  frontend/static/image/icon-play.svg
  frontend/static/image/icon-plus.svg
  frontend/static/image/icon-repeat.svg
  frontend/static/image/icon-rotate-ccw.svg
  frontend/static/image/icon-search-active.svg
  frontend/static/image/icon-search.svg
  frontend/static/image/icon-trash.svg
  frontend/static/image/id_card.png
  frontend/static/image/logo-title.png
  frontend/static/image/logo.png
  frontend/static/js/API/API.js
  frontend/static/js/API/apikey.js
  frontend/static/js/index.js
  frontend/static/js/json/memberData.json
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Chart.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/NotFound.js
  frontend/static/js/views/PlayControl.js
  frontend/static/js/views/Search.js
  frontend/static/js/views/Splash.js
  package-lock.json
  package.json
  server.js
Labels: Build, Pair

#79 :hammer: Chore : 메인 Title, 각 페이지 Title 수정
  frontend/index.html
  frontend/static/js/views/Chart.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/NotFound.js
  frontend/static/js/views/PlayControl.js
  frontend/static/js/views/Search.js
Labels: Chore, Pair

#80 :sparkles: Feat: 이전곡, 다음곡 재생기능 구현
  frontend/static/js/views/PlayControl.js
Labels: Feat, Pair

#84 Feat/issue 71
  frontend/static/css/playcontrol.css
  frontend/static/image/icon-random.svg
  frontend/static/image/icon-repeat.svg
  frontend/static/image/icon-rotate-ccw.svg
  frontend/static/js/index.js
  frontend/static/js/views/PlayControl.js
Labels: Feat, Style, Pair, Refactor

#86 Feat/issue 71
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/PlayControl.js
Labels: Feat, Pair

#87 :sparkles: Feat: 한곡 반복 기능구현 및 랜덤재생, endAudio 불필요한 로직 제거
  frontend/static/js/views/PlayControl.js
Labels: Feat, Chore, Pair

#88 :sparkles: Feat: playcontrol 노래 제목이 긴 경우 slide 효과 구현
  frontend/static/css/playcontrol.css
  frontend/static/js/views/PlayControl.js
Labels: Feat, Style, Pair

#89 Build: develop에서 main으로 merge(v1.0.1)
  frontend/static/css/playcontrol.css
  frontend/static/image/icon-random.svg
  frontend/static/image/icon-repeat.svg
  frontend/static/image/icon-rotate-ccw.svg
  frontend/static/js/index.js
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/PlayControl.js
Labels: Build, Pair

#90 Feat/issue 72
  frontend/static/css/home.css
  frontend/static/js/json/memberData.json
  frontend/static/js/views/Home.js
Labels: Feat, Style, Pair

#91 Feat/issue 81
  frontend/static/image/NotFound.png
  frontend/static/image/logo-title.png
  frontend/static/image/search-default.png
Labels: Style, Pair

#93 :sparkles: Feat: search 페이지 기본 화면 이미지 추가
  frontend/static/css/search.css
  frontend/static/js/views/Search.js
Labels: Feat, Style, Pair

#94 Feat/issue 83
  frontend/static/css/search.css
  frontend/static/js/views/Search.js
Labels: Style, Pair, Refactor

#95 Build: develop에서 main으로 merge(v1.0.2)
  frontend/static/css/home.css
  frontend/static/css/search.css
  frontend/static/image/NotFound.png
  frontend/static/image/logo-title.png
  frontend/static/image/search-default.png
  frontend/static/js/json/memberData.json
  frontend/static/js/views/Home.js
  frontend/static/js/views/Search.js
Labels: Build, Pair

#96 Feat/issue 81
  frontend/static/css/notfound.css
  frontend/static/css/search.css
  frontend/static/css/style.css
  frontend/static/js/index.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/NotFound.js
  frontend/static/js/views/PlayControl.js
  frontend/static/js/views/Search.js
Labels: Feat, Style, Chore, Pair

#97 Feat/issue 92
  frontend/index.html
  frontend/static/css/style.css
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Chart.js
  frontend/static/js/views/Search.js
Labels: Feat, Style, MarkUp, Pair

#98 Feat/issue 83
  frontend/static/css/reset.css
  frontend/static/css/search.css
  frontend/static/image/search-no-result.png
  frontend/static/js/views/Search.js
Labels: Feat, Style, MarkUp, Pair

#99 Feat/issue 85
  frontend/static/css/reset.css
  frontend/static/css/style.css
  frontend/static/image/loading.gif
  frontend/static/js/API/apikey.js
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/Search.js
Labels: Feat, Style, Chore, Pair

#100 :sparkles: Feat: chart 페이지 렌더링 전 로딩화면 구현
  frontend/static/js/views/Chart.js
Labels: Feat, Pair

#101 :hammer: Build: develop에서 main으로 merge(v1.0.3)
  README.md
  frontend/index.html
  frontend/static/css/notfound.css
  frontend/static/css/search.css
  frontend/static/css/style.css
  frontend/static/image/loading.gif
  frontend/static/image/search-no-result.png
  frontend/static/js/API/apikey.js
  frontend/static/js/index.js
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Chart.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/NotFound.js
  frontend/static/js/views/PlayControl.js
  frontend/static/js/views/Search.js
Labels: Feat, Style, Build, Pair

#102 Feat/issue 71
  frontend/static/css/playcontrol.css
  frontend/static/image/icon-mute.svg
  frontend/static/image/icon-speaker.svg
  frontend/static/js/views/PlayControl.js
Labels: Feat, Style, Pair

#104 :lipstick: Design : playcontrol 재생바 effect 추가, 음향 조절바 스타일 수정
  frontend/static/css/playcontrol.css
  frontend/static/css/style.css
  frontend/static/js/views/PlayControl.js
Labels: Style, Pair

#105 :bug: Fix : playcontrol 페이지 레이아웃 이탈 현상 내부 스크롤 추가하여 수정
  frontend/static/css/playcontrol.css
  frontend/static/css/style.css
  frontend/static/js/views/PlayControl.js
Labels: Style, Fix, Pair

#106 Feat/issue 82
  frontend/static/css/home.css
  frontend/static/image/icon-arrow-hover.png
  frontend/static/image/icon-arrow.png
  frontend/static/js/views/Home.js
Labels: Style, Chore, MarkUp, Pair

#107 Feat/issue 82
  frontend/static/css/home.css
  frontend/static/js/views/Home.js
Labels: Feat, Style, Pair

#108 Feat/issue 82
  frontend/static/css/home.css
  frontend/static/css/style.css
  frontend/static/js/views/Home.js
Labels: Chore, Pair

#109 Fix/issue 51
  frontend/static/js/index.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/Search.js
Labels: Fix, Chore, Pair
