Repository SuDaJo/MusicPlayer, pull requests merged in 2023-02, with the labels that each got.

#16 Chore/issue 14
  frontend/index.html
  frontend/static/css/chart.css
  frontend/static/css/home.css
  frontend/static/css/myplaylist.css
  frontend/static/css/navbar.css
  frontend/static/css/playcontrol.css
  frontend/static/css/reset.css
  frontend/static/css/search.css
  frontend/static/css/style.css
  frontend/static/image/album-img.png
  frontend/static/image/album-title-img.png
  frontend/static/image/icon-arrow-left.svg
  frontend/static/image/icon-backward.svg
  frontend/static/image/icon-forward.svg
  frontend/static/image/icon-home-active.svg
  frontend/static/image/icon-home.svg
  frontend/static/image/icon-music-active.svg
  frontend/static/image/icon-music.svg
  frontend/static/image/icon-pause.svg
  frontend/static/image/icon-play-gray.svg
  frontend/static/image/icon-play-white.svg
  frontend/static/image/icon-play.svg
  frontend/static/image/icon-playList-active.svg
  frontend/static/image/icon-playList.svg
  frontend/static/image/icon-plus.svg
  frontend/static/image/icon-repeat.svg
  frontend/static/image/icon-rotate-ccw.svg
  frontend/static/image/icon-search-active.svg
  frontend/static/image/icon-search.svg
  frontend/static/image/icon-trash.svg
  frontend/static/image/logo-title.png
  frontend/static/image/logo.png
  frontend/static/js/index.js
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Chart.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/NotFound.js
  frontend/static/js/views/PlayControl.js
  frontend/static/js/views/Search.js
  index.html
  server.js
Labels: Feat, Chore, MarkUp, Pair

#18 Feat/issue 17
  frontend/index.html
  frontend/static/js/index.js
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Chart.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/PlayControl.js
  frontend/static/js/views/Search.js
  server.js
Labels: Feat, Pair

#21 :bug: Fix : 요소가 계속 추가되는 현상 수정
  frontend/static/js/views/Home.js
Labels: Feat, Fix, Pair

#22 :bug: Fix : 요소가 추가되는 버그 코드수정
  frontend/static/js/index.js
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Home.js
Labels: Feat, Fix, Pair

#23 :bug: Fix : 홈 네비게이션 버튼 클릭시 요소가 계속 추가 생성되는 현상 수정
  frontend/static/js/index.js
  frontend/static/js/views/Home.js
Labels: Fix, Pair

#25 :bug: Fix : 페이지 이동시 라우터 렌더링 오류해결
  frontend/static/js/index.js
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Chart.js
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/Search.js
Labels: Feat, Fix, Pair

#26 :sparkles: Feat: 차트 화면 요소 생성
  frontend/static/js/views/Chart.js
Labels: Feat, Pair

#28 :sparkles: Feat: playList 페이지 요소 추가
  frontend/static/js/views/Chart.js
  frontend/static/js/views/MyplayList.js
Labels: Feat, Pair

#31 :sparkles: Feat: home 화면 카테고리 추가(최신곡)
  frontend/static/js/views/Home.js
Labels: Feat, Pair

#34 Fix/issue 33
  frontend/index.html
  frontend/static/js/index.js
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Chart.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/Search.js
Labels: Feat, Fix, Pair

#35 Feat/issue 32
  frontend/static/js/index.js
  frontend/static/js/views/Chart.js
  frontend/static/js/views/PlayControl.js
Labels: Feat, Pair

#37 :sparkles: Feat: playControl 뒤로가기 기능 구현
  frontend/static/js/index.js
  frontend/static/js/views/PlayControl.js
Labels: Feat, Pair

#39 Feat/issue 38
  frontend/static/css/playcontrol.css
  frontend/static/js/API/API.js
  frontend/static/js/API/apikey.js
  frontend/static/js/views/Home.js
Labels: Feat, Pair

#41 :sparkles: Feat: 랜덤 아티스트 생성, 쿼리문에 적용
  frontend/static/js/API/API.js
  frontend/static/js/views/Home.js
Labels: Feat, Pair

#42 Feat/issue 40
  frontend/static/css/home.css
  frontend/static/css/playcontrol.css
  frontend/static/js/index.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/PlayControl.js
Labels: Feat, Style, Fix, Pair

#43 Feat/issue 40
  frontend/static/css/home.css
  frontend/static/js/views/Home.js
Labels: Feat, Style, Chore, Pair

#45 Feat/issue 44
  frontend/static/js/views/Home.js
  frontend/static/js/views/Search.js
Labels: Feat, Pair

#47 Feat/issue 46
  frontend/index.html
  frontend/static/css/navbar.css
  frontend/static/css/style.css
  frontend/static/js/index.js
  frontend/static/js/views/Splash.js
Labels: Feat, Style, MarkUp, Pair

#50 :bug: Fix : playcontrol 페이지로 이동 시 splash 화면이 뜨는 버그 수정
  frontend/static/js/index.js
Labels: Fix, Pair

#53 Feat/issue 52
  frontend/static/js/API/API.js
  frontend/static/js/index.js
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Home.js
  frontend/static/js/views/PlayControl.js
Labels: Feat, Chore, Pair

#54 Feat/issue 52
  README.md
  frontend/static/js/index.js
  frontend/static/js/views/PlayControl.js
  frontend/static/js/views/Search.js
Labels: Feat, Chore, Docs, Pair

#55 :sparkles: Feat: playcontrol 음악 재생 기능 구현
  frontend/static/js/views/PlayControl.js
Labels: Feat, Pair

#57 :bug: Fix : 재생바 드래그 시 위치 정상적으로 못 잡는 현상, 노래 전체 재생 시간에 맞게 표시하도록 수정
  frontend/static/js/views/PlayControl.js
Labels: Fix, Pair

#60 :bug: Fix : Search 페이지에서 돋보기 버튼 작동 안하는 현상 수정, 이벤트 함수 분리
  frontend/static/js/views/Search.js
Labels: Fix, Pair, Refactor

#61 Feat/issue 58
  frontend/static/css/myplaylist.css
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/PlayControl.js
Labels: Feat, Style, Pair

#62 :sparkles: Feat: playlist 삭제 기능 구현
  frontend/static/js/views/MyplayList.js
Labels: Feat, Pair

#63 Feat/issue 58
  frontend/static/css/myplaylist.css
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/PlayControl.js
Labels: Feat, Pair

#64 Feat/issue 58
  frontend/static/js/views/MyplayList.js
  frontend/static/js/views/Search.js
Labels: Feat, Fix, Pair

#66 :recycle: Refactor: setLocalStorage로 중복 로직 분리
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/PlayControl.js
  frontend/static/js/views/Search.js
Labels: Pair, Refactor

#68 Feat/issue 67
  frontend/static/css/chart.css
  frontend/static/css/reset.css
  frontend/static/js/views/AbstractView.js
  frontend/static/js/views/Chart.js
  frontend/static/js/views/Home.js
Labels: Feat, Style, Pair, Refactor

#69 Feat/issue 67
  frontend/static/css/chart.css
  frontend/static/css/reset.css
  frontend/static/js/views/Chart.js
Labels: Feat, Style, Pair
